### ISSUE TITLE
naming clash with the misanthropy library

### ISSUE THREAD

**Issue by cortesi** [mdegans/misanthropic#5]
Hi there - I maintain a library that has an almost identical name, and very similar features:

https://github.com/cortesi/misanthropy

It's a funny coincidence that we had the same naming idea, but since my library predates yours by some months would you be open to changing the name of your package? Having to libraries with nearly identical features and names would, I feel, be too confusing.

**Comment by mdegans** [comment]
I personally notified you about this a month ago when I first released the crate. You did not respond. When I wrote the crate I searched for `anthropic` and `misanthropic`. I did not see your crate. I apologize for the confusion but the crate is already linked to in many places and being used downstream. Renaming it at this point would cause too much breakage. Had you let me know a month ago about your concerns when I first contacted you I would have complied. Now it is too late. Very sorry, but no.

**Comment by cortesi** [comment]
Very well - I'll refer people to this issue if there is ever any confusion. As we discussed on Discord, you did a poor job vetting the name for this package which can happen to anyone, but your response to your mistake shows lack of character and poor citizenship. You sent me a Discord DM (which I didn't see) a month ago which is not a reasonable way to contact me about a Github project, and you did not ask about the package naming confusion in your message. All that this shows is that you were well aware of the naming clash right from the outset and chose to go ahead anyway.

**Comment by mdegans** [comment]
When I started writing the package, I searched `crates.io` for `misanthropic` and `anthropic`. I did not see your crate. When I published, there was no clash. When I went to the Anthropic discord and saw your project was when I became aware. I frankly didn't think you would mind, but I sent a message anyway. You were online but did not respond. I am not going to break downstream usage and all the in-links in various places because you got back to me around version `0.3.0` a month later. Sorry.

**Comment by mdegans** [comment]
> and you did not ask about the package naming confusion in your message

I did mention our projects were similar, yes I did and I included the name. I did inform you.

**Comment by cortesi** [comment]
I've said this over and over on Discord, but I'll do so again here for the final time: I am not interested in discussing this with you ad nauseam. I asked you politely to do the right thing, you refused. That's the end of the story - no discussion needed, no further action required, let's move on. Yet you just keep going - I blocked you on Discord after you confronted me there, now you're continuing over here. This should have been 5 minutes of our combined time, total.

I've unsubbed from this ticket - please DO NOT contact me again by any other means. Good luck with your project.

**Comment by mdegans** [comment]
I did refuse. You asked me to change the name a month too late and i just don't feel like it. It's the obvious name which you should have picked but didn't. There isn't a shruggie to describe my lack of care here.

> you just keep going

Lol. You're the one who opened an issue to kvetch. Toodles.
